// AI Code Generator
const codeExamples = {
    'card': `// Responsive card component
export function ProductCard({ product }) {
  return (
    <div className="card">
      <img src={product.image} alt={product.name} />
      <div className="card-content">
<h3>{product.name}</h3>
<p>{product.description}</p>
<div className="card-footer">
  <span className="price">${product.price}</span>
  <button className="add-to-cart">Add to Cart</button>
</div>
      </div>
    </div>
  );
}`,
    
    'login': `// Login form with validation
import { useState } from 'react';

export function LoginForm() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [errors, setErrors] = useState({});

  const validate = () => {
    const newErrors = {};
    if (!email.includes('@')) newErrors.email = 'Invalid email';
    if (password.length < 8) newErrors.password = 'Password too short';
    return newErrors;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const validationErrors = validate();
    if (Object.keys(validationErrors).length === 0) {
      // Submit login
    } else {
      setErrors(validationErrors);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} />
      {errors.email && <span className="error">{errors.email}</span>}
      <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
      {errors.password && <span className="error">{errors.password}</span>}
      <button type="submit">Login</button>
    </form>
  );
}`,
    
    'navbar': `// Navbar with dark mode toggle
import { useState, useEffect } from 'react';

export function Navbar() {
  const [darkMode, setDarkMode] = useState(false);

  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [darkMode]);

  return (
    <nav className="navbar">
      <div className="navbar-brand">MyApp</div>
      <div className="navbar-links">
<a href="/">Home</a>
<a href="/about">About</a>
<a href="/contact">Contact</a>
      </div>
      <button onClick={() => setDarkMode(!darkMode)} className="dark-mode-toggle">
{darkMode ? '🌙' : '☀️'}
      </button>
    </nav>
  );
}`
};

document.getElementById('generateBtn').addEventListener('click', function() {
    const prompt = document.getElementById('aiPrompt').value.toLowerCase();
    let code = '';
    
    if (prompt.includes('card')) {
code = codeExamples.card;
    } else if (prompt.includes('login')) {
code = codeExamples.login;
    } else if (prompt.includes('nav')) {
code = codeExamples.navbar;
    } else {
code = `// AI-generated code for: "${prompt}"
// Note: This is a simulation. Real AI would generate actual code.

function ${prompt.split(' ')[0] || 'Component'}() {
  // TODO: Implement ${prompt}
  return (
    <div className="${prompt.split(' ')[0]?.toLowerCase() || 'component'}">
      <h1>${prompt}</h1>
      <p>This would be generated by AI in real life.</p>
    </div>
  );
}`;
    }
    
    const output = document.getElementById('aiOutput');
    output.innerHTML = `
<div class="code-line"><span class="code-comment">// AI-generated ${prompt.split(' ')[0] || 'component'}</span></div>
<div class="code-line"><span class="code-comment">// Generated at ${new Date().toLocaleTimeString()}</span></div>
<div class="code-line"></div>
    `;
    
    // Add code line by line with typing effect
    const lines = code.split('\n');
    let lineIndex = 0;
    
    function typeNextLine() {
if (lineIndex < lines.length) {
    const lineDiv = document.createElement('div');
    lineDiv.className = 'code-line';
    
    // Simple syntax highlighting
    let lineText = lines[lineIndex];
    lineText = lineText
.replace(/\/\/.*$/g, '<span class="code-comment">$&</span>')
.replace(/'.*?'|".*?"|`.*?`/g, '<span class="code-string">$&</span>')
.replace(/\b(import|export|function|return|const|let|if|else)\b/g, '<span class="code-keyword">$1</span>');
    
    lineDiv.innerHTML = lineText;
    output.appendChild(lineDiv);
    lineIndex++;
    
    output.scrollTop = output.scrollHeight;
    setTimeout(typeNextLine, 50);
}
    }
    
    typeNextLine();
    
    // Button animation
    this.innerHTML = '<i class="fas fa-sync fa-spin me-2"></i>Generating...';
    setTimeout(() => {
this.innerHTML = '<i class="fas fa-code me-2"></i>Generate Code';
    }, 1500);
});

document.getElementById('explainBtn').addEventListener('click', function() {
    const output = document.getElementById('aiOutput');
    const explanation = document.createElement('div');
    explanation.className = 'code-line';
    explanation.innerHTML = '<span class="code-comment">// AI Explanation: This code follows modern React patterns with hooks for state management.</span>';
    output.appendChild(explanation);
    output.scrollTop = output.scrollHeight;
});

// Performance Slider
document.getElementById('performanceSlider').addEventListener('input', function() {
    const score = this.value;
    document.getElementById('performanceScore').textContent = score;
    document.getElementById('performanceBar').style.width = score + '%';
    
    // Update color based on score
    let color;
    if (score < 50) {
color = 'linear-gradient(90deg, #ff0000, #ff4444)';
    } else if (score < 90) {
color = 'linear-gradient(90deg, #ff8800, #ffaa44)';
    } else {
color = 'linear-gradient(90deg, #00ff00, #44ff44)';
    }
    document.getElementById('performanceBar').style.background = color;
});

// Tech badges hover effect
document.querySelectorAll('.tech-badge').forEach(badge => {
    badge.addEventListener('mouseenter', function() {
const colors = [
    'linear-gradient(135deg, var(--dev-purple), var(--ai-green))',
    'linear-gradient(135deg, var(--js-yellow), var(--dev-purple))',
    'linear-gradient(135deg, var(--react-blue), var(--ai-green))'
];
this.style.background = colors[Math.floor(Math.random() * colors.length)];
    });
    
    badge.addEventListener('mouseleave', function() {
this.style.background = '';
    });
});

// Auto-type prompt example
const prompts = [
    'A responsive card component',
    'A login form with validation',
    'A navbar with dark mode toggle',
    'A todo app with drag and drop',
    'A weather widget with animations'
];

let promptIndex = 0;
let charIndex = 0;
let isDeleting = false;
const promptElement = document.getElementById('aiPrompt');

function typePrompt() {
    const currentPrompt = prompts[promptIndex];
    
    if (isDeleting) {
promptElement.value = currentPrompt.substring(0, charIndex - 1);
charIndex--;
    } else {
promptElement.value = currentPrompt.substring(0, charIndex + 1);
charIndex++;
    }
    
    if (!isDeleting && charIndex === currentPrompt.length) {
setTimeout(() => isDeleting = true, 2000);
    } else if (isDeleting && charIndex === 0) {
isDeleting = false;
promptIndex = (promptIndex + 1) % prompts.length;
    }
    
    setTimeout(typePrompt, isDeleting ? 50 : 100);
}

// Start typing effect after page loads
setTimeout(typePrompt, 1000);
